### ISSUE TITLE
Noarch package may have some problems

### ISSUE THREAD

**Issue by jochym** [conda-forge/itsdangerous-feedstock#9]
I am trying to update a feedstock for ASE. New version depends on flask and thus on itsdangerous. But it seems the noarch package does not get recognized as installed and the build breaks (https://circleci.com/gh/jochym/ase-feedstock/66) for python < 3.6. Note that the package is actually installed (see the logs). Maybe something is wrong with the noarch build system? 
I have worked around the issue by pinning the itsdangerous and werkzug packages for py<36 but this is an ugly workaround (see https://circleci.com/gh/jochym/ase-feedstock/78). Maybe it is too early to use noarch in production?

**Comment by nicoddemus** [comment]
The error seems to be this one:

```
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/itsdangerous/
```

So it seems someone in the chain depends on `itsdangerous` but does not declare it on their `meta.yml`.

**Comment by jochym** [comment]
I do not think so. The dependence is pulled in and installed. Both of them (same problem with werkzug). It is just not detected as installed by setuptools. Look at the linked logs. The only difference is the installed package py_x or py35_x for both. I do not understand the system enough to find the cause. Any ideas?

**Comment by nicoddemus** [comment]
>  It is just not detected as installed by setuptools. Look at the linked logs.

You are right, conda declares it is installed.

I'm not sure what's happening, but the `noarch` package seems to be working fine:


```
name: itsdangerous-test

dependencies:
  - itsdangerous =0.24 py_2
```

```
λ conda env update
Fetching package metadata .........
Solving package specifications: .
itsdangerous-0 100% |###############################| Time: 0:00:00  12.24 MB/s
setuptools-36. 100% |###############################| Time: 0:00:00  31.51 MB/s
#
# To activate this environment, use:
# > activate itsdangerous-test
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


λ activate itsdangerous-test

(itsdangerous-test) C:\Users\bruno\itstest
λ conda list
# packages in environment at W:\Miniconda\envs\itsdangerous-test:
#
certifi                   2016.2.28                py35_0    mirror
itsdangerous              0.24                       py_2    mirror-conda-forge
pip                       9.0.1                    py35_1    mirror
python                    3.5.0                         1    mirror
setuptools                36.4.0                   py35_1    mirror
wheel                     0.29.0                   py35_0    mirror
wincertstore              0.2                      py35_0    mirror

(itsdangerous-test)
λ python
Python 3.5.0 |Continuum Analytics, Inc.| (default, Sep 15 2015, 09:20:39) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import itsdangerous
>>>

(itsdangerous-test)
λ pip list --format=columns
Package      Version
------------ ---------
certifi      2016.2.28
itsdangerous 0.24
pip          9.0.1
setuptools   36.4.0
wheel        0.29.0
wincertstore 0.2

```

We also use other `noarch` packages without issues. I'm out of ideas what to do to suggest to debug this issue though. Can you reproduce it locally or only in CircleCI?

**Comment by jochym** [comment]
I did not try. I will, but probably tomorrow. I have to go now. Thanks for your help.

**Comment by Lnaden** [comment]
We're also having this problem [over on our package](https://github.com/omnia-md/conda-recipes/pull/844#issuecomment-349807723) which is using `Flask`, which uses `itsdangerous`. 

Near as I can tell, Conda installs the `noarch` version from conda-forge during `conda-build`, then when setup tools goes to install the package, `itsdangerous` is not recognized by `setuptools` as the installed, but only in Python 2.7 and 3.5; Python 3.6 works fine. We are having the exact same symptoms as the @jochym, and I can also confirm that pip does correctly list the package as installed, even if we install `itsdangerous` through conda. Sorry I don't have any additional debug info, but I figured it would be worth adding this, even if to keep the issue alive.

The good news is I think @jochym's workaround will work for us for now.

**Comment by jochym** [comment]
It works for build but not for runtime unfortunately. I have reproduced the problem locally as well. The programs fail to work with these two noarch packages. I had to pin to earlier versions but this is just a workaround - please consider reverting to arch packages. The same issue concerns werkzeug and nglview (https://github.com/conda-forge/nglview-feedstock/issues/5)

**Comment by jochym** [comment]
It is solved now. It was my fault at the end. Sorry, and thanks for your help!
